owner: TransparentLC
repo: status

sites:
  - name: Cloudreve
    url: https://file.akarin.dev/api/v3/site/config
  - name: frp tunnel
    check: tcp-ping
    url: frp-tunnel.akarin.dev
    port: 1919
  - name: Mail server
    check: tcp-ping
    url: smtp.akarin.dev
    port: 465
  - name: Fleur de Lapin
    url: $SECRET_URL_FLEUR
    expectedStatusCodes:
      - 400
  - name: Amausaan
    url: $SECRET_URL_AMAUSAAN
    expectedStatusCodes:
      - 400

status-website:
  baseUrl: /status
  logoUrl: https://gcore.jsdelivr.net/gh/TransparentLC/transparentlc.github.io/img/avatar.jpg
  name: Akarin Server
  introTitle: Akarin Server's status page
  introMessage: Real-time monitoring for self-hosted services on Akarin Server, powered by [Upptime](https://github.com/upptime/upptime).
  favicon: https://gcore.jsdelivr.net/gh/TransparentLC/transparentlc.github.io/img/favicon.png
  robotsText: "User-agent: * \n Disallow: /"
  metaTags:
    - name: robots
      content: noindex
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
