owner: TransparentLC
repo: status

sites:
  - name: Cloudreve
    url: https://file.akarin.dev/api/v4/site/ping
  - name: frp tunnel
    check: tcp-ping
    url: $SECRET_URL_FRP
    port: 1919
  - name: Mail server
    check: tcp-ping
    url: smtp.akarin.dev
    port: 465
  - name: Hakurei Shrine
    url: $SECRET_URL_HAKUREI
    expectedStatusCodes:
      - 400
  - name: Moriya Shrine
    url: $SECRET_URL_MORIYA
    expectedStatusCodes:
      - 400
  - name: Hath
    url: $SECRET_URL_HATH
    __dangerous__disable_verify_host: true
  - name: Crypto Lab
    url: https://crypto-lab.akarin.dev/
  - name: Qsticker Archive
    url: https://qsticker.akarin.dev/
  - name: dufs file sharing
    url: https://fuwafuwa.akarin.dev/__dufs__/health

status-website:
  baseUrl: /status
  logoUrl: https://gcore.jsdelivr.net/gh/TransparentLC/transparentlc.github.io/img/avatar.jpg
  name: Akarin Server
  introTitle: Akarin Server's status page
  introMessage: Real-time monitoring for self-hosted services on Akarin Server, powered by [Upptime](https://github.com/upptime/upptime).
  favicon: https://gcore.jsdelivr.net/gh/TransparentLC/transparentlc.github.io/img/favicon.png
  themeUrl: https://gcore.jsdelivr.net/gh/TransparentLC/status/assets/theme.css
  robotsText: "User-agent: * \n Disallow: /"
  metaTags:
    - name: robots
      content: noindex
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
